### ISSUE TITLE
Where is the definition of function opt?

### ISSUE THREAD

**Issue by Zhangc2024** [SpaceNaN/fuzzjit#2]
The paper mentions the use of a wrapper function named "opt" to encapsulate code snippets, but i don't find the definition of the "opt" function.

**Comment by nonetype** [comment]
You can find the "opt" function's definition from codePrefix/Suffix of each profile (V8Profile, JSCProfile, ...).

https://github.com/SpaceNaN/fuzzjit/blob/a3d3f6da7f7f8577476892d6135eee6c50afc7ad/Sources/FuzzilliCli/Profiles/V8Profile.swift#L275-L346

**Comment by Zhangc2024** [comment]
Thank you for your response. I found the "opt" function, and it's a very clever idea.
